// unicode.h — Unicode character data and algorithms used by ojs
// (identifiers, case mapping, regex property classes, normalization).
// Tables: unicode_data.c (generated by tools/gen_unicode.py from the UCD).
#ifndef OJS_UNICODE_H
#define OJS_UNICODE_H

#include <stdint.h>

struct urange_set { const uint32_t* r; int n; };          // n [start, end] pairs, sorted
struct uprop { const char* names; struct urange_set set; };   // names: "Long|alias|alias"
struct upairs { const uint32_t* p; int n; };              // n (key, value) pairs, sorted by key
struct umulti { const uint32_t* p; int n; };              // n rows: cp, count, c1, c2, c3
struct udecomp { const uint32_t* e; int n; const uint32_t* seq; };   // rows: cp, compat<<7|len, offset
struct ucompose { const uint32_t* p; int n; };            // rows: first, second, composite (sorted)

extern const struct urange_set uni_id_start, uni_id_continue;
extern const struct uprop uni_gc[], uni_binary[], uni_sc[], uni_scx[];
extern const struct upairs uni_upper, uni_lower, uni_fold, uni_ccc;
extern const struct umulti uni_special_upper, uni_special_lower;
extern const struct udecomp uni_decomp;
extern const struct ucompose uni_compose;

int uni_in(const struct urange_set* s, uint32_t cp);
int uni_id_start_cp(uint32_t cp);       // ID_Start plus $ and _
int uni_id_continue_cp(uint32_t cp);    // ID_Continue plus $, ZWNJ, ZWJ
uint32_t uni_simple_upper(uint32_t cp);
uint32_t uni_simple_lower(uint32_t cp);
uint32_t uni_simple_fold(uint32_t cp);
// full mappings: writes up to 3 code points, returns count
int uni_full_upper(uint32_t cp, uint32_t* out);
int uni_full_lower(uint32_t cp, uint32_t* out);
int uni_ccc_of(uint32_t cp);
// property lookup for regex \p{...}: kind 0 = General_Category value,
// 1 = binary property, 2 = Script, 3 = Script_Extensions.
// Returns the range set (complemented sets are built by the caller), or
// NULL if unknown. *complement_assigned is set for Cn/C (unassigned).
const struct urange_set* uni_find_prop(int kind, const char* name, int* is_cn);
int uni_is_white_space(uint32_t cp);

#endif
