// GENERATED by tools/gen_web_tables.py - fixed atom ids for known names.
// Atom 0 is "no name". Tag atoms are T_*, attribute atoms A_*; ids are
// shared (one table), so a name that is both keeps a single id.
#ifndef WEB_ATOMS_GEN_H
#define WEB_ATOMS_GEN_H

#define T_a 1
#define T_abbr 2
#define T_acronym 3
#define T_address 4
#define T_applet 5
#define T_area 6
#define T_article 7
#define T_aside 8
#define T_audio 9
#define T_b 10
#define T_base 11
#define T_basefont 12
#define T_bdi 13
#define T_bdo 14
#define T_bgsound 15
#define T_big 16
#define T_blink 17
#define T_blockquote 18
#define T_body 19
#define T_br 20
#define T_button 21
#define T_canvas 22
#define T_caption 23
#define T_center 24
#define T_cite 25
#define T_code 26
#define T_col 27
#define T_colgroup 28
#define T_data 29
#define T_datalist 30
#define T_dd 31
#define T_del 32
#define T_details 33
#define T_dfn 34
#define T_dialog 35
#define T_dir 36
#define T_div 37
#define T_dl 38
#define T_dt 39
#define T_em 40
#define T_embed 41
#define T_fieldset 42
#define T_figcaption 43
#define T_figure 44
#define T_font 45
#define T_footer 46
#define T_form 47
#define T_frame 48
#define T_frameset 49
#define T_h1 50
#define T_h2 51
#define T_h3 52
#define T_h4 53
#define T_h5 54
#define T_h6 55
#define T_head 56
#define T_header 57
#define T_hgroup 58
#define T_hr 59
#define T_html 60
#define T_i 61
#define T_iframe 62
#define T_image 63
#define T_img 64
#define T_input 65
#define T_ins 66
#define T_isindex 67
#define T_kbd 68
#define T_keygen 69
#define T_label 70
#define T_legend 71
#define T_li 72
#define T_link 73
#define T_listing 74
#define T_main 75
#define T_map 76
#define T_mark 77
#define T_marquee 78
#define T_menu 79
#define T_menuitem 80
#define T_meta 81
#define T_meter 82
#define T_nav 83
#define T_nobr 84
#define T_noembed 85
#define T_noframes 86
#define T_noscript 87
#define T_object 88
#define T_ol 89
#define T_optgroup 90
#define T_option 91
#define T_output 92
#define T_p 93
#define T_param 94
#define T_picture 95
#define T_plaintext 96
#define T_pre 97
#define T_progress 98
#define T_q 99
#define T_rb 100
#define T_rp 101
#define T_rt 102
#define T_rtc 103
#define T_ruby 104
#define T_s 105
#define T_samp 106
#define T_script 107
#define T_search 108
#define T_section 109
#define T_select 110
#define T_slot 111
#define T_small 112
#define T_source 113
#define T_span 114
#define T_strike 115
#define T_strong 116
#define T_style 117
#define T_sub 118
#define T_summary 119
#define T_sup 120
#define T_table 121
#define T_tbody 122
#define T_td 123
#define T_template 124
#define T_textarea 125
#define T_tfoot 126
#define T_th 127
#define T_thead 128
#define T_time 129
#define T_title 130
#define T_tr 131
#define T_track 132
#define T_tt 133
#define T_u 134
#define T_ul 135
#define T_var 136
#define T_video 137
#define T_wbr 138
#define T_xmp 139
#define T_svg 140
#define T_math 141
#define T_foreignobject 142
#define T_desc 143
#define T_mi 144
#define T_mo 145
#define T_mn 146
#define T_ms 147
#define T_mtext 148
#define T_annotation_xml 149
#define T_path 150
#define T_circle 151
#define T_rect 152
#define T_line 153
#define T_polyline 154
#define T_polygon 155
#define T_ellipse 156
#define T_g 157
#define T_use 158
#define T_defs 159
#define T_symbol 160
#define T_lineargradient 161
#define T_radialgradient 162
#define T_stop 163
#define T_clippath 164
#define T_mask 165
#define T_text 166
#define T_tspan 167
#define A_id 168
#define A_class 169
#define A_href 170
#define A_src 171
#define A_alt 172
#define A_type 173
#define A_name 174
#define A_value 175
#define A_width 176
#define A_height 177
#define A_colspan 178
#define A_rowspan 179
#define A_align 180
#define A_valign 181
#define A_bgcolor 182
#define A_color 183
#define A_face 184
#define A_size 185
#define A_border 186
#define A_cellpadding 187
#define A_cellspacing 188
#define A_hidden 189
#define A_rel 190
#define A_media 191
#define A_charset 192
#define A_content 193
#define A_http_equiv 194
#define A_lang 195
#define A_disabled 196
#define A_checked 197
#define A_selected 198
#define A_placeholder 199
#define A_action 200
#define A_method 201
#define A_target 202
#define A_start 203
#define A_reversed 204
#define A_srcset 205
#define A_sizes 206
#define A_loading 207
#define A_role 208
#define A_aria_hidden 209
#define A_aria_label 210
#define A_for 211
#define A_rows 212
#define A_cols 213
#define A_readonly 214
#define A_multiple 215
#define A_maxlength 216
#define A_background 217
#define A_vlink 218
#define A_alink 219
#define A_nowrap 220
#define A_clear 221
#define A_noshade 222
#define A_compact 223
#define A_viewbox 224
#define A_fill 225
#define A_stroke 226
#define A_stroke_width 227
#define A_d 228
#define A_cx 229
#define A_cy 230
#define A_r 231
#define A_rx 232
#define A_ry 233
#define A_x 234
#define A_y 235
#define A_x1 236
#define A_y1 237
#define A_x2 238
#define A_y2 239
#define A_points 240
#define A_transform 241
#define A_opacity 242
#define A_fill_opacity 243
#define A_stroke_opacity 244
#define A_fill_rule 245
#define A_offset 246
#define A_stop_color 247
#define A_preserveaspectratio 248
#define A_xmlns 249
#define A_version 250
#define A_data_src 251
#define A_poster 252
#define A_encoding 253
#define A_open 254
#define A_style T_style
#define A_title T_title
#define A_dir T_dir
#define A_label T_label
#define A_span T_span
#define A_text T_text
#define A_link T_link
#define ATOM_KNOWN_COUNT 255
static const char* const atom_known_names[ATOM_KNOWN_COUNT] = {
    "",
    "a",
    "abbr",
    "acronym",
    "address",
    "applet",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "basefont",
    "bdi",
    "bdo",
    "bgsound",
    "big",
    "blink",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "center",
    "cite",
    "code",
    "col",
    "colgroup",
    "data",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "dialog",
    "dir",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "font",
    "footer",
    "form",
    "frame",
    "frameset",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "image",
    "img",
    "input",
    "ins",
    "isindex",
    "kbd",
    "keygen",
    "label",
    "legend",
    "li",
    "link",
    "listing",
    "main",
    "map",
    "mark",
    "marquee",
    "menu",
    "menuitem",
    "meta",
    "meter",
    "nav",
    "nobr",
    "noembed",
    "noframes",
    "noscript",
    "object",
    "ol",
    "optgroup",
    "option",
    "output",
    "p",
    "param",
    "picture",
    "plaintext",
    "pre",
    "progress",
    "q",
    "rb",
    "rp",
    "rt",
    "rtc",
    "ruby",
    "s",
    "samp",
    "script",
    "search",
    "section",
    "select",
    "slot",
    "small",
    "source",
    "span",
    "strike",
    "strong",
    "style",
    "sub",
    "summary",
    "sup",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "time",
    "title",
    "tr",
    "track",
    "tt",
    "u",
    "ul",
    "var",
    "video",
    "wbr",
    "xmp",
    "svg",
    "math",
    "foreignobject",
    "desc",
    "mi",
    "mo",
    "mn",
    "ms",
    "mtext",
    "annotation-xml",
    "path",
    "circle",
    "rect",
    "line",
    "polyline",
    "polygon",
    "ellipse",
    "g",
    "use",
    "defs",
    "symbol",
    "lineargradient",
    "radialgradient",
    "stop",
    "clippath",
    "mask",
    "text",
    "tspan",
    "id",
    "class",
    "href",
    "src",
    "alt",
    "type",
    "name",
    "value",
    "width",
    "height",
    "colspan",
    "rowspan",
    "align",
    "valign",
    "bgcolor",
    "color",
    "face",
    "size",
    "border",
    "cellpadding",
    "cellspacing",
    "hidden",
    "rel",
    "media",
    "charset",
    "content",
    "http-equiv",
    "lang",
    "disabled",
    "checked",
    "selected",
    "placeholder",
    "action",
    "method",
    "target",
    "start",
    "reversed",
    "srcset",
    "sizes",
    "loading",
    "role",
    "aria-hidden",
    "aria-label",
    "for",
    "rows",
    "cols",
    "readonly",
    "multiple",
    "maxlength",
    "background",
    "vlink",
    "alink",
    "nowrap",
    "clear",
    "noshade",
    "compact",
    "viewbox",
    "fill",
    "stroke",
    "stroke-width",
    "d",
    "cx",
    "cy",
    "r",
    "rx",
    "ry",
    "x",
    "y",
    "x1",
    "y1",
    "x2",
    "y2",
    "points",
    "transform",
    "opacity",
    "fill-opacity",
    "stroke-opacity",
    "fill-rule",
    "offset",
    "stop-color",
    "preserveaspectratio",
    "xmlns",
    "version",
    "data-src",
    "poster",
    "encoding",
    "open",
};

#endif
