; Embedded TrueType faces for the web engine (src/web/font.c).
; Subsets generated by tools/subset_fonts.sh; licenses in fonts/.
; Paths are relative to the repository root (make runs there).

section .rodata
align 4

%macro FONT 2
global %1, %1_end
%1:
incbin %2
%1_end:
align 4
%endmacro

FONT wfd_sans_r,  "fonts/NotoSans-Regular.ttf"
FONT wfd_sans_b,  "fonts/NotoSans-Bold.ttf"
FONT wfd_sans_i,  "fonts/NotoSans-Italic.ttf"
FONT wfd_sans_bi, "fonts/NotoSans-BoldItalic.ttf"
FONT wfd_serif_r, "fonts/NotoSerif-Regular.ttf"
FONT wfd_serif_b, "fonts/NotoSerif-Bold.ttf"
FONT wfd_serif_i, "fonts/NotoSerif-Italic.ttf"
FONT wfd_mono_r,  "fonts/NotoSansMono-Regular.ttf"
FONT wfd_mono_b,  "fonts/NotoSansMono-Bold.ttf"
FONT wfd_sym,     "fonts/DejaVuSans-Symbols.ttf"

; must stay the LAST section (AGENTS.md: .note.GNU-stack swallows code after it)
section .note.GNU-stack noalloc noexec nowrite progbits
