#!/usr/bin/env python3
"""Convert a BDF bitmap font (e.g. terminus-font ter-uNNn.bdf) into the okernel
font-array format used by src/graphics.c.

Usage:
    python3 tools/bdf2font.py ter-u32n.bdf -o src/font_data.c

Emits `font8x16[N][H*BPR]` for ASCII 32..126 (the 95 glyphs the kernel
renders), MSB-first per row, matching graphics.c's font_bit() reader. Also
prints the #define values to drop into graphics.h and the extern second
dimension to update.

Handles the FONTBOUNDINGBOX/BBX compositing so glyphs land in the right cell
position (Terminus stores each glyph pre-composed into the full cell, but the
general code copes with inset BBXes too).
"""
import sys, os, argparse

def parse_bdf(path):
    W = H = xb = yb = None
    glyphs = {}
    cur = None
    state = None
    with open(path, encoding="latin-1") as f:
        for line in f:
            t = line.strip()
            if t.startswith("FONTBOUNDINGBOX"):
                _, w, h, xo, yo = t.split()
                W, H, xb, yb = int(w), int(h), int(xo), int(yo)
            elif t.startswith("STARTCHAR"):
                cur = {}
                state = "meta"
            elif t == "BITMAP":
                state = "bitmap"
            elif t == "ENDCHAR":
                if cur and "enc" in cur:
                    glyphs[cur["enc"]] = cur
                cur = None
                state = None
            elif state == "bitmap" and t:
                cur.setdefault("bm", []).append(t)
            elif state == "meta":
                if t.startswith("ENCODING"):
                    cur["enc"] = int(t.split()[1])
                elif t.startswith("BBX"):
                    _, gw, gh, xo, yo = t.split()
                    cur["gw"], cur["gh"] = int(gw), int(gh)
                    cur["xoff"], cur["yoff"] = int(xo), int(yo)
    return W, H, xb, yb, glyphs

def composite(g, W, H, xb, yb):
    cell = [[0] * W for _ in range(H)]
    gw, gh = g["gw"], g["gh"]
    xoff, yoff = g["xoff"], g["yoff"]
    rows = g.get("bm", [])
    for r in range(gh):
        hexrow = rows[r] if r < len(rows) else ""
        bits = int(hexrow, 16) if hexrow else 0
        for c in range(gw):
            if (bits >> (gw - 1 - c)) & 1:
                col = (xoff - xb) + c
                row = (yb - yoff) + (H - gh) + r
                if 0 <= col < W and 0 <= row < H:
                    cell[row][col] = 1
    return cell

def cell_bytes(cell, W, bpr):
    out = []
    for r in range(len(cell)):
        v = 0
        for c in range(W):
            if cell[r][c]:
                v |= 1 << (W - 1 - c)
        for b in range(bpr):
            out.append((v >> (8 * (bpr - 1 - b))) & 0xFF)
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("-o", "--output", default="src/font_data.c")
    ap.add_argument("--first", type=int, default=32)
    ap.add_argument("--last", type=int, default=126)
    args = ap.parse_args()

    W, H, xb, yb, glyphs = parse_bdf(args.input)
    if W is None:
        raise SystemExit("FONTBOUNDINGBOX not found")
    bpr = (W + 7) // 8
    n = args.last - args.first + 1

    lines = []
    lines.append("#include <stdint.h>")
    lines.append("// Auto-generated by tools/bdf2font.py from "
                 f"{os.path.basename(args.input)} ({W}x{H}).")
    lines.append(f"// ASCII {args.first}..{args.last}, MSB-first rows, {bpr} bytes/row.")
    lines.append(f"const uint8_t font8x16[{n}][{H * bpr}] = {{")
    for c in range(args.first, args.last + 1):
        g = glyphs.get(c)
        cell = composite(g, W, H, xb, yb) if g else [[0] * W for _ in range(H)]
        body = ", ".join(f"0x{b:02x}" for b in cell_bytes(cell, W, bpr))
        ch = chr(c) if 32 < c < 127 else "?"
        lines.append(f"    /* {c:3d} '{ch}' */ {{ {body} }},")
    lines.append("};")
    text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(text)

    print(f"wrote {args.output}: {W}x{H}, {n} glyphs, {bpr} bytes/row")
    print()
    print("Set in src/graphics.h:")
    print(f"  #define FONT_W {W}")
    print(f"  #define FONT_H {H}")
    print(f"  #define FONT_SCALE 1   // font is already at display size")
    print("and update the extern in graphics.h + add src/font_data.o to the Makefile:")
    print(f"  extern const uint8_t font8x16[{n}][{H * bpr}];")

if __name__ == "__main__":
    main()
