#!/usr/bin/env python3
"""Generate src/web/entities.h (WHATWG named character references, from
Python's html.entities.html5) and src/web/atoms_gen.h (known tag/attribute
names with fixed atom ids). Run from the repo root:
    python3 tools/gen_web_tables.py
"""
import html.entities

def c_str(b):
    out = []
    for ch in b:
        if 32 <= ch < 127 and ch not in (34, 92):
            out.append(chr(ch))
        else:
            out.append('\\x%02x""' % ch)
    return '"' + ''.join(out) + '"'

ents = sorted(html.entities.html5.items(), key=lambda kv: kv[0].encode())
with open('src/web/entities.h', 'w') as f:
    f.write('// GENERATED by tools/gen_web_tables.py - WHATWG named character references.\n')
    f.write('// Sorted by name (bytewise). Names include the trailing ";" when the\n')
    f.write('// spec requires it; legacy names appear both with and without it.\n')
    f.write('#ifndef WEB_ENTITIES_H\n#define WEB_ENTITIES_H\n\n')
    f.write('struct went { const char* name; const char* utf8; };\n')
    f.write('#define WENT_COUNT %d\n' % len(ents))
    f.write('#define WENT_MAXLEN %d\n' % max(len(k) for k, _ in ents))
    f.write('static const struct went went_table[WENT_COUNT] = {\n')
    for k, v in ents:
        f.write('    { %s, %s },\n' % (c_str(k.encode()), c_str(v.encode('utf-8', 'surrogatepass'))))
    f.write('};\n\n#endif\n')

TAGS = """a abbr acronym address applet area article aside audio b base basefont bdi bdo bgsound big
blink blockquote body br button canvas caption center cite code col colgroup data datalist dd del
details dfn dialog dir div dl dt em embed fieldset figcaption figure font footer form frame frameset
h1 h2 h3 h4 h5 h6 head header hgroup hr html i iframe image img input ins isindex kbd keygen label
legend li link listing main map mark marquee menu menuitem meta meter nav nobr noembed noframes
noscript object ol optgroup option output p param picture plaintext pre progress q rb rp rt rtc
ruby s samp script search section select slot small source span strike strong style sub summary
sup table tbody td template textarea tfoot th thead time title tr track tt u ul var video wbr xmp
svg math foreignobject desc mi mo mn ms mtext annotation-xml path circle rect line polyline polygon
ellipse g use defs symbol lineargradient radialgradient stop clippath mask text tspan""".split()

ATTRS = """id class style href src alt title type name value width height colspan rowspan align
valign bgcolor color face size border cellpadding cellspacing hidden rel media charset content
http-equiv lang dir disabled checked selected placeholder action method target start reversed
srcset sizes loading role aria-hidden aria-label for label rows cols readonly multiple maxlength
span background text link vlink alink nowrap clear noshade compact viewbox fill stroke stroke-width
d cx cy r rx ry x y x1 y1 x2 y2 points transform opacity fill-opacity stroke-opacity fill-rule
offset stop-color preserveaspectratio xmlns version data-src poster encoding open start""".split()

seen = set()
TAGS = [t for t in TAGS if not (t in seen or seen.add(t))]
ATTRS_ALL = list(dict.fromkeys(ATTRS))
BOTH = [a for a in ATTRS_ALL if a in seen]       # attr names that are also tags
ATTRS = [a for a in ATTRS_ALL if a not in seen]

def ident(n):
    return n.replace('-', '_')

with open('src/web/atoms_gen.h', 'w') as f:
    f.write('// GENERATED by tools/gen_web_tables.py - fixed atom ids for known names.\n')
    f.write('// Atom 0 is "no name". Tag atoms are T_*, attribute atoms A_*; ids are\n')
    f.write('// shared (one table), so a name that is both keeps a single id.\n')
    f.write('#ifndef WEB_ATOMS_GEN_H\n#define WEB_ATOMS_GEN_H\n\n')
    i = 1
    for t in TAGS:
        f.write('#define T_%s %d\n' % (ident(t), i)); i += 1
    for a in ATTRS:
        f.write('#define A_%s %d\n' % (ident(a), i)); i += 1
    # names that are both tags and attrs share the tag's id
    for both in BOTH:
        f.write('#define A_%s T_%s\n' % (ident(both), ident(both)))
    f.write('#define ATOM_KNOWN_COUNT %d\n' % i)
    f.write('static const char* const atom_known_names[ATOM_KNOWN_COUNT] = {\n    "",\n')
    for n in TAGS + ATTRS:
        f.write('    "%s",\n' % n)
    f.write('};\n\n#endif\n')
CHARSETS = [  # (codec, labels...)
    ('cp1252', 'windows-1252', 'iso-8859-1', 'latin1', 'us-ascii', 'ascii', 'iso8859-1', 'l1', 'cp1252', 'x-cp1252'),
    ('cp1251', 'windows-1251', 'cp1251', 'x-cp1251'),
    ('cp1250', 'windows-1250', 'cp1250', 'x-cp1250'),
    ('koi8_r', 'koi8-r', 'koi8r', 'koi'),
    ('koi8_u', 'koi8-u', 'koi8-ru'),
    ('iso8859_2', 'iso-8859-2', 'latin2', 'iso8859-2', 'l2'),
    ('iso8859_5', 'iso-8859-5', 'iso8859-5', 'cyrillic'),
    ('iso8859_7', 'iso-8859-7', 'greek', 'iso8859-7'),
    ('iso8859_15', 'iso-8859-15', 'latin9', 'iso8859-15', 'l9'),
    ('cp1253', 'windows-1253', 'cp1253'),
    ('cp1254', 'windows-1254', 'iso-8859-9', 'latin5', 'cp1254'),
    ('cp1257', 'windows-1257', 'cp1257'),
    ('mac_roman', 'macintosh', 'mac', 'x-mac-roman'),
    ('cp437', 'ibm437', 'cp437'),
    ('cp866', 'ibm866', 'cp866'),
]
with open('src/web/charsets.h', 'w') as f:
    f.write('// GENERATED by tools/gen_web_tables.py - single-byte code pages (high half).\n')
    f.write('#ifndef WEB_CHARSETS_H\n#define WEB_CHARSETS_H\n#include <stdint.h>\n\n')
    f.write('struct wcs { const char* const* labels; const uint16_t* hi; };\n')
    for idx, (codec, *labels) in enumerate(CHARSETS):
        hi = []
        for b in range(128, 256):
            try:
                ch = bytes([b]).decode(codec)
                hi.append(ord(ch))
            except UnicodeDecodeError:
                # WHATWG windows-1252 maps undefined 0x81/8D/8F/90/9D to C1 controls
                hi.append(b if codec == 'cp1252' else 0xFFFD)
        f.write('static const uint16_t wcs_hi_%d[128] = {%s};\n' % (idx, ','.join(str(v) for v in hi)))
        f.write('static const char* const wcs_lab_%d[] = {%s, 0};\n' % (idx, ','.join('"%s"' % l for l in labels)))
    f.write('#define WCS_COUNT %d\n' % len(CHARSETS))
    f.write('static const struct wcs wcs_table[WCS_COUNT] = {\n')
    for idx in range(len(CHARSETS)):
        f.write('    { wcs_lab_%d, wcs_hi_%d },\n' % (idx, idx))
    f.write('};\n\n#endif\n')
import math
with open('src/web/colortab.h', 'w') as f:
    f.write('// GENERATED by tools/gen_web_tables.py - integer tables for CSS color math.\n')
    f.write('#ifndef WEB_COLORTAB_H\n#define WEB_COLORTAB_H\n#include <stdint.h>\n\n')
    # linear (0..4095 -> 0..1) to sRGB 0..255
    vals = []
    for li in range(4096):
        c = li / 4095.0
        s = 12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055
        vals.append(max(0, min(255, int(round(s * 255)))))
    f.write('static const uint8_t lin2srgb[4096] = {%s};\n' % ','.join(map(str, vals)))
    # sin(deg) * 65536 for 0..359
    f.write('static const int32_t sin_deg[360] = {%s};\n' %
            ','.join(str(int(round(math.sin(math.radians(d)) * 65536))) for d in range(360)))
    f.write('\n#endif\n')
print("entities:", len(ents), "atoms:", i, "charsets:", len(CHARSETS))
