#!/usr/bin/env python3
# Generates src/crypto/roots.c: the trusted root CA store.
#
# Source: Mozilla's certdata.txt (the NSS builtin trust store) — the
# authoritative list, read directly so the TRUST BITS and the
# SERVER_DISTRUST_AFTER dates come with it (the Debian/Ubuntu PEM bundle
# drops both: it kept roots Mozilla had removed or limited). Only roots
# with CKA_TRUST_SERVER_AUTH = CKT_NSS_TRUSTED_DELEGATOR are embedded. Each
# entry embeds the full root certificate DER; the SubjectPublicKeyInfo and
# subject Name are views into it. certverify.c anchors a chain either at an
# in-flight certificate carrying a root's key (SPKI hash match) or at a
# flight certificate ISSUED by a root (subject name + key identifier match,
# signature verified with the root's key), and refuses leaves issued after
# a root's distrust-after date.
#
#   curl -sSLo /tmp/certdata.txt \
#     https://raw.githubusercontent.com/nss-dev/nss/master/lib/ckfw/builtins/certdata.txt
#   python3 tools/gen_roots.py /tmp/certdata.txt
import hashlib, re, sys

# ---- minimal DER walker ----
def tlv(b, i):
    tag = b[i]; i += 1
    l = b[i]; i += 1
    if l & 0x80:
        n = l & 0x7F
        l = int.from_bytes(b[i:i + n], "big"); i += n
    return tag, i, l          # tag, content start, content length

def children(b, start, length):
    out, i, end = [], start, start + length
    while i < end:
        tag, cs, cl = tlv(b, i)
        out.append((tag, i, cs, cl))   # tag, element start, content start, content len
        i = cs + cl
    return out

OID_RSA = bytes.fromhex("2a864886f70d010101")
OID_EC = bytes.fromhex("2a8648ce3d0201")
OID_P256 = bytes.fromhex("2a8648ce3d030107")
OID_P384 = bytes.fromhex("2b81040022")

def parse(der):
    _, cs, cl = tlv(der, 0)                     # Certificate
    tbs = children(der, cs, cl)[0]              # TBSCertificate
    f = children(der, tbs[2], tbs[3])
    k = 1 if f[0][0] == 0xA0 else 0             # [0] version present?
    # serial, sigalg, issuer, validity, subject, spki
    subj = f[k + 4]
    spki = f[k + 5]
    subj_der = (subj[1], subj[2] + subj[3] - subj[1])
    spki_der = (spki[1], spki[2] + spki[3] - spki[1])
    # SubjectKeyIdentifier (2.5.29.14) from the [3] extensions, if any
    ski = None
    for el in f[k + 6:]:
        if el[0] != 0xA3:
            continue
        exts = children(der, el[2], el[3])[0]
        for ext in children(der, exts[2], exts[3]):
            parts = children(der, ext[2], ext[3])
            if der[parts[0][2]:parts[0][2] + parts[0][3]] == bytes.fromhex("551d0e"):
                octet = parts[-1]                       # extnValue OCTET STRING
                inner = children(der, octet[2], octet[3])[0]   # KeyIdentifier OCTET STRING
                ski = (inner[2], inner[3])
    alg = children(der, spki[2], spki[3])[0]    # AlgorithmIdentifier
    a = children(der, alg[2], alg[3])
    oid = der[a[0][2]:a[0][2] + a[0][3]]
    ktype = None
    if oid == OID_RSA:
        ktype = "X509_KEY_RSA"
    elif oid == OID_EC and len(a) > 1:
        curve = der[a[1][2]:a[1][2] + a[1][3]]
        ktype = {OID_P256: "X509_KEY_EC_P256", OID_P384: "X509_KEY_EC_P384"}.get(curve)
    return subj_der, spki_der, ktype, ski

# ---- certdata.txt ----
def octal(block):
    return bytes(int(m, 8) for m in re.findall(r"\\([0-7]{3})", block))

def load_certdata(path):
    text = open(path, encoding="utf-8").read()
    certs, trust = [], {}
    for obj in re.split(r"\n\s*\n", text):
        if "CKA_CLASS CK_OBJECT_CLASS CKO_CERTIFICATE" in obj:
            label = re.search(r'CKA_LABEL UTF8 "(.*)"', obj).group(1)
            der = octal(re.search(r"CKA_VALUE MULTILINE_OCTAL\n(.*?)\nEND", obj, re.S).group(1))
            m = re.search(r"CKA_NSS_SERVER_DISTRUST_AFTER MULTILINE_OCTAL\n(.*?)\nEND", obj, re.S)
            distrust = octal(m.group(1)).decode() if m else None
            certs.append((label, der, distrust))
        elif "CKO_NSS_TRUST" in obj:
            m = re.search(r"CKA_CERT_SHA1_HASH MULTILINE_OCTAL\n(.*?)\nEND", obj, re.S)
            s = re.search(r"CKA_TRUST_SERVER_AUTH CK_TRUST (\S+)", obj)
            if m and s:
                trust[octal(m.group(1))] = s.group(1)
    return certs, trust

def utc_fields(t):
    # UTCTime YYMMDDHHMMSSZ (what certdata uses) -> C initializer
    m = re.fullmatch(r"(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)(\d\d)Z", t)
    if not m:
        raise ValueError("unexpected distrust time " + t)
    yy, mo, dd, hh, mi, ss = (int(x) for x in m.groups())
    year = 2000 + yy if yy < 50 else 1900 + yy
    return f"{{ {year}, {mo}, {dd}, {hh}, {mi}, {ss} }}"

def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__ or "usage: gen_roots.py certdata.txt")
    certs, trust = load_certdata(sys.argv[1])
    out = ["// roots.c — GENERATED by tools/gen_roots.py from Mozilla certdata.txt",
           "// — do not edit by hand. Trusted root CA store (roots with",
           "// CKA_TRUST_SERVER_AUTH = CKT_NSS_TRUSTED_DELEGATOR) for TLS 1.3",
           "// certificate verification. Each entry: the root certificate DER,",
           "// views of its SubjectPublicKeyInfo and subject Name, the SHA-256 of",
           "// the SPKI (see certverify.c for both anchoring modes) and Mozilla's",
           "// server distrust-after date, if any.",
           '#include "roots.h"', '#include "x509.h"', ""]
    entries, seen = [], set()
    for label, der, distrust in certs:
        if trust.get(hashlib.sha1(der).digest()) != "CKT_NSS_TRUSTED_DELEGATOR":
            continue
        try:
            subj, spki, ktype, ski = parse(der)
        except Exception as e:
            print(f"skip (parse): {label}: {e}", file=sys.stderr)
            continue
        if not ktype:
            print(f"skip (key type): {label}", file=sys.stderr)
            continue
        h = hashlib.sha256(der[spki[0]:spki[0] + spki[1]]).digest()
        key = (h, der[subj[0]:subj[0] + subj[1]])
        if key in seen:
            continue
        seen.add(key)
        sym = "root_" + str(len(entries))
        toks = [f"0x{x:02X}" for x in der]
        out.append(f"// {label}" + (f" (server distrust after {distrust})" if distrust else ""))
        out.append(f"static const uint8_t {sym}[{len(der)}] = {{")
        for i in range(0, len(toks), 16):
            out.append("    " + ", ".join(toks[i:i + 16]) + ",")
        out.append("};")
        out.append(f"static const uint8_t {sym}_hash[32] = {{")
        out.append("    " + ", ".join(f"0x{x:02X}" for x in h) + ",")
        out.append("};")
        entries.append((sym, len(der), spki, subj, label, ktype, ski, distrust))
    out.append("")
    out.append("const x509_root x509_roots[] = {")
    for sym, ln, spki, subj, label, ktype, ski, distrust in entries:
        esc = label.replace("\\", "\\\\").replace('"', '\\"')
        sk = f"{sym} + {ski[0]}, {ski[1]}" if ski else "0, 0"
        da = f"1, {utc_fields(distrust)}" if distrust else "0, { 0, 0, 0, 0, 0, 0 }"
        out.append(f'    {{ {sym} + {spki[0]}, {spki[1]}, {sym}_hash, "{esc}", {ktype},')
        out.append(f'      {sym}, {ln}, {sym} + {subj[0]}, {subj[1]}, {sk},')
        out.append(f'      {da} }},')
    out.append("};")
    out.append("")
    out.append(f"const int x509_root_count = {len(entries)};")
    with open("src/crypto/roots.c", "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote src/crypto/roots.c with {len(entries)} roots "
          f"({sum(1 for e in entries if e[7])} with a distrust-after date)", file=sys.stderr)

if __name__ == "__main__":
    main()
