#!/usr/bin/env python3
# Generates src/crypto/roots.c: the trusted root CA store.
#
# Source: the Mozilla CA program as packaged by Debian/Ubuntu
# (/usr/share/ca-certificates/mozilla/*.crt — roots trusted for TLS server
# authentication). Each entry embeds the full root certificate DER; the
# SubjectPublicKeyInfo and subject Name are views into it. certverify.c
# anchors a chain either at an in-flight certificate carrying a root's key
# (SPKI hash match) or at a flight certificate ISSUED by a root (subject
# name + key identifier match, signature verified with the root's key).
#
#   python3 tools/gen_roots.py [cert-dir]
import base64, hashlib, os, sys, glob

DEFAULT_DIR = "/usr/share/ca-certificates/mozilla"

# ---- minimal DER walker ----
def tlv(b, i):
    tag = b[i]; i += 1
    l = b[i]; i += 1
    if l & 0x80:
        n = l & 0x7F
        l = int.from_bytes(b[i:i + n], "big"); i += n
    return tag, i, l          # tag, content start, content length

def children(b, start, length):
    out, i, end = [], start, start + length
    while i < end:
        tag, cs, cl = tlv(b, i)
        out.append((tag, i, cs, cl))   # tag, element start, content start, content len
        i = cs + cl
    return out

OID_RSA = bytes.fromhex("2a864886f70d010101")
OID_EC = bytes.fromhex("2a8648ce3d0201")
OID_P256 = bytes.fromhex("2a8648ce3d030107")
OID_P384 = bytes.fromhex("2b81040022")

def parse(der):
    _, cs, cl = tlv(der, 0)                     # Certificate
    tbs = children(der, cs, cl)[0]              # TBSCertificate
    f = children(der, tbs[2], tbs[3])
    k = 1 if f[0][0] == 0xA0 else 0             # [0] version present?
    # serial, sigalg, issuer, validity, subject, spki
    subj = f[k + 4]
    spki = f[k + 5]
    subj_der = (subj[1], subj[2] + subj[3] - subj[1])
    spki_der = (spki[1], spki[2] + spki[3] - spki[1])
    # SubjectKeyIdentifier (2.5.29.14) from the [3] extensions, if any
    ski = None
    for el in f[k + 6:]:
        if el[0] != 0xA3:
            continue
        exts = children(der, el[2], el[3])[0]
        for ext in children(der, exts[2], exts[3]):
            parts = children(der, ext[2], ext[3])
            if der[parts[0][2]:parts[0][2] + parts[0][3]] == bytes.fromhex("551d0e"):
                octet = parts[-1]                       # extnValue OCTET STRING
                inner = children(der, octet[2], octet[3])[0]   # KeyIdentifier OCTET STRING
                ski = (inner[2], inner[3])
    alg = children(der, spki[2], spki[3])[0]    # AlgorithmIdentifier
    a = children(der, alg[2], alg[3])
    oid = der[a[0][2]:a[0][2] + a[0][3]]
    ktype = None
    if oid == OID_RSA:
        ktype = "X509_KEY_RSA"
    elif oid == OID_EC and len(a) > 1:
        curve = der[a[1][2]:a[1][2] + a[1][3]]
        ktype = {OID_P256: "X509_KEY_EC_P256", OID_P384: "X509_KEY_EC_P384"}.get(curve)
    return subj_der, spki_der, ktype, ski

def cn_of(der, subj):
    # best effort: the last CN (2.5.4.3) or O (2.5.4.10) in the subject
    s, n = subj
    name, org = None, None
    for rdn in children(der, *tlv(der, s)[1:]):
        for atv in children(der, rdn[2], rdn[3]):
            parts = children(der, atv[2], atv[3])
            oid = der[parts[0][2]:parts[0][2] + parts[0][3]]
            val = der[parts[1][2]:parts[1][2] + parts[1][3]].decode("utf-8", "replace")
            if oid == bytes.fromhex("550403"): name = val
            if oid == bytes.fromhex("55040a"): org = val
    return name or org or "root"

def main():
    d = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DIR
    files = sorted(glob.glob(os.path.join(d, "*.crt")) + glob.glob(os.path.join(d, "*.pem")))
    out = ["// roots.c — GENERATED by tools/gen_roots.py — do not edit by hand.",
           "// Trusted root CA store (Mozilla CA program, TLS server auth) for",
           "// TLS 1.3 certificate verification. Each entry: the root certificate",
           "// DER, views of its SubjectPublicKeyInfo and subject Name, and the",
           "// SHA-256 of the SPKI (see certverify.c for both anchoring modes).",
           '#include "roots.h"', '#include "x509.h"', ""]
    entries = []
    seen = set()
    for path in files:
        pem = open(path).read()
        b64 = "".join(l for l in pem.splitlines() if l and "-----" not in l)
        der = base64.b64decode(b64)
        try:
            subj, spki, ktype, ski = parse(der)
        except Exception as e:
            print(f"skip (parse): {path}: {e}", file=sys.stderr)
            continue
        if not ktype:
            print(f"skip (key type): {os.path.basename(path)}", file=sys.stderr)
            continue
        h = hashlib.sha256(der[spki[0]:spki[0] + spki[1]]).digest()
        if (h, der[subj[0]:subj[0] + subj[1]]) in seen:
            continue
        seen.add((h, der[subj[0]:subj[0] + subj[1]]))
        cn = cn_of(der, subj)
        sym = "root_" + str(len(entries))
        toks = [f"0x{x:02X}" for x in der]
        out.append(f"// {cn}")
        out.append(f"static const uint8_t {sym}[{len(der)}] = {{")
        for i in range(0, len(toks), 16):
            out.append("    " + ", ".join(toks[i:i + 16]) + ",")
        out.append("};")
        out.append(f"static const uint8_t {sym}_hash[32] = {{")
        out.append("    " + ", ".join(f"0x{x:02X}" for x in h) + ",")
        out.append("};")
        entries.append((sym, len(der), spki, subj, cn, ktype, ski))
    out.append("")
    out.append("const x509_root x509_roots[] = {")
    for sym, ln, spki, subj, cn, ktype, ski in entries:
        esc = cn.replace("\\", "\\\\").replace('"', '\\"')
        sk = f"{sym} + {ski[0]}, {ski[1]}" if ski else "0, 0"
        out.append(f'    {{ {sym} + {spki[0]}, {spki[1]}, {sym}_hash, "{esc}", {ktype},')
        out.append(f'      {sym}, {ln}, {sym} + {subj[0]}, {subj[1]}, {sk} }},')
    out.append("};")
    out.append("")
    out.append(f"const int x509_root_count = {len(entries)};")
    with open("src/crypto/roots.c", "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote src/crypto/roots.c with {len(entries)} roots", file=sys.stderr)

if __name__ == "__main__":
    main()
