#!/usr/bin/env python3
# Generates src/crypto/roots.c from PEM root certificates.
# Embeds each root's SubjectPublicKeyInfo DER + a name string; matching is by
# SHA-256 over the SPKI DER (see certverify.c). Rerun to refresh the store.
import base64, hashlib, subprocess, sys, os

ROOTS = [
    "SSL.com_TLS_ECC_Root_CA_2022",     # example.com chain (SSL.com)
    "SSL.com_TLS_RSA_Root_CA_2022",
    "ISRG_Root_X1",                      # Let's Encrypt (RSA-4096)
    "ISRG_Root_X2",                      # Let's Encrypt (ECDSA P-384)
    "GTS_Root_R1",                       # Google Trust Services
    "GTS_Root_R4",
    "DigiCert_Global_Root_G2",
    "Amazon_Root_CA_1",
    "Amazon_Root_CA_3",
    "USERTrust_RSA_Certification_Authority",
    "USERTrust_ECC_Certification_Authority",
    "GlobalSign_Root_CA_-_R3",
    "Sectigo_Public_Server_Authentication_Root_R46",
    "Sectigo_Public_Server_Authentication_Root_E46",
]

def pem_spki_and_name(path):
    # SPKI DER
    out = subprocess.run(["openssl", "x509", "-in", path, "-noout", "-pubkey"],
                         capture_output=True, text=True).stdout
    b64 = "".join(l for l in out.splitlines() if "-----" not in l)
    spki = base64.b64decode(b64)
    # subject (one-line)
    name = subprocess.run(["openssl", "x509", "-in", path, "-noout", "-subject",
                           "-nameopt", "sep_multiline,utf8"],
                          capture_output=True, text=True).stdout
    # compact: take CN or fall back to whole thing
    cn = ""
    for line in name.splitlines():
        line = line.strip()
        if line.startswith("CN="):
            cn = line[3:]
            break
    if not cn:
        cn = os.path.basename(path).replace(".pem", "")
    # key type from the SPKI algorithm OID
    oid = subprocess.run(["openssl", "x509", "-in", path, "-noout", "-text"],
                         capture_output=True, text=True).stdout
    if "id-ecPublicKey" in oid:
        ktype = "X509_KEY_EC_P384" if "secp384r1" in oid else "X509_KEY_EC_P256"
    elif "Public-Key" in oid:
        ktype = "X509_KEY_RSA"
    else:
        ktype = "X509_KEY_NONE"
    return spki, cn, ktype

def main():
    out = []
    out.append("// roots.c — GENERATED by tools/gen_roots.py — do not edit by hand.")
    out.append("// Trusted root CA store for TLS 1.3 certificate verification.")
    out.append("// Each entry: raw SubjectPublicKeyInfo DER + its SHA-256 (the SPKI")
    out.append("// hash the chain verifier matches against, see certverify.c).")
    out.append('#include "roots.h"')
    out.append('#include "x509.h"')
    out.append("")
    entries = []
    for name in ROOTS:
        path = f"/etc/ssl/certs/{name}.pem"
        if not os.path.exists(path):
            print(f"skip (missing): {name}", file=sys.stderr)
            continue
        spki, cn, ktype = pem_spki_and_name(path)
        sym = "root_spki_" + "".join(ch if ch.isalnum() else "_" for ch in cn)[:48]
        toks = [f"0x{b:02X}" for b in spki]
        lines = []
        cur = []
        cur_len = 0
        for t in toks:
            add = len(t) + (1 if cur else 0)
            if cur_len + add > 66:
                lines.append(", ".join(cur) + ",")
                cur = [t]
                cur_len = len(t)
            else:
                cur.append(t)
                cur_len += add
        if cur:
            lines.append(", ".join(cur) + ",")
        out.append(f"static const uint8_t {sym}[] = {{")
        for l in lines:
            out.append(f"    {l}")
        out.append("};")
        h = hashlib.sha256(spki).digest()
        hsym = sym.replace("root_spki_", "root_hash_")
        out.append(f"static const uint8_t {hsym}[32] = {{")
        out.append("    " + ", ".join(f"0x{b:02X}" for b in h) + ",")
        out.append("};")
        entries.append((sym, hsym, len(spki), cn, ktype))
        print(f"embedded: {cn} ({len(spki)} bytes, {ktype})", file=sys.stderr)
    out.append("")
    out.append("const x509_root x509_roots[] = {")
    for sym, hsym, ln, cn, ktype in entries:
        esc = cn.replace("\\", "\\\\").replace('"', '\\"')
        out.append(f'    {{ {sym}, sizeof({sym}), {hsym}, "{esc}", {ktype} }},')
    out.append("};")
    out.append("")
    out.append(f"const int x509_root_count = {len(entries)};")
    out.append("")
    with open("src/crypto/roots.c", "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote src/crypto/roots.c with {len(entries)} roots", file=sys.stderr)

if __name__ == "__main__":
    main()
