#!/usr/bin/env python3
"""Convert a PSF (PC Screen Font) console font into the okernel bitmap-font
array format used by src/graphics.c.

Usage:
    python3 tools/psf2font.py INPUT.psf[.gz] [-o src/font_data.c]

Emits `font8x16[95][H*BPR]` for ASCII 32..126 (the 95 glyphs the kernel
renders), MSB-first per row, matching graphics.c's font_bit() reader. Also
prints the #define values to drop into graphics.h and the extern second
dimension to update.

Supports PSF2 (arbitrary width/height — e.g. a 16x32 Terminus) and PSF1
(8px wide only).
"""
import sys, os, struct, gzip, argparse

def load(path):
    data = open(path, "rb").read()
    if data[:2] == b"\x1f\x8b":  # gzip
        data = gzip.decompress(data)
    return data

def parse_psf(data):
    # PSF2
    if data[:4] == b"\x72\xb5\x4a\x86":
        magic, version, hdrlen, flags, length, charsize, height, width = \
            struct.unpack_from("<IIIIIIII", data, 0)
        if version != 0:
            raise SystemExit(f"unsupported PSF2 version {version}")
        glyphs = data[hdrlen:hdrlen + length * charsize]
        return width, height, charsize, length, glyphs
    # PSF1
    if data[:2] == b"\x36\x04":
        magic, mode, charsize = struct.unpack_from("<HB B", data, 0)
        length = 512 if (mode & 1) else 256
        hdrlen = 4
        glyphs = data[hdrlen:hdrlen + length * charsize]
        return 8, charsize, charsize, length, glyphs
    raise SystemExit("not a PSF1/PSF2 font (magic mismatch)")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input")
    ap.add_argument("-o", "--output", default="src/font_data.c")
    args = ap.parse_args()

    data = load(args.input)
    width, height, charsize, nglyphs, glyphs = parse_psf(data)
    bpr = (width + 7) // 8
    if charsize != height * bpr:
        print(f"warning: charsize {charsize} != height*bpr {height*bpr}; "
              f"using height*bpr", file=sys.stderr)
        charsize = height * bpr

    first, last = 32, 126
    n = last - first + 1
    out = []
    for c in range(first, last + 1):
        if c >= nglyphs:
            # pad missing glyphs with blank
            out.append(bytes(charsize))
        else:
            g = glyphs[c * charsize:(c + 1) * charsize]
            out.append(g)
    flat = b"".join(out)

    lines = []
    lines.append("// Auto-generated by tools/psf2font.py from "
                 f"{os.path.basename(args.input)} "
                 f"({width}x{height}, {nglyphs} glyphs).")
    lines.append(f"// ASCII 32..126, MSB-first rows, {bpr} bytes/row.")
    lines.append(f"const uint8_t font8x16[{n}][{height * bpr}] = {{")
    for i, c in enumerate(range(first, last + 1)):
        row = flat[i * charsize:(i + 1) * charsize]
        body = ", ".join(f"0x{b:02x}" for b in row)
        ch = chr(c) if 32 < c < 127 else "?"
        lines.append(f"    /* {c:3d} '{ch}' */ {{ {body} }},")
    lines.append("};")
    text = "\n".join(lines) + "\n"

    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(text)

    print(f"wrote {args.output}: {width}x{height}, {n} glyphs, {bpr} bytes/row")
    print()
    print("Set in src/graphics.h:")
    print(f'  #define FONT_W {width}')
    print(f'  #define FONT_H {height}')
    print(f'  #define FONT_SCALE 1   // font is already at display size')
    print("and update the extern in graphics.h:")
    print(f'  extern const uint8_t font8x16[{n}][{height * bpr}];')

if __name__ == "__main__":
    main()
